# Generated by Django 5.1.1 on 2024-09-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0002_waitinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='time_slot',
        ),
    ]
