# Generated by Django 5.1.1 on 2024-09-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0009_table_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='time_slot',
        ),
    ]
